// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// rcpp_hello
List rcpp_hello();
RcppExport SEXP _ecaRbioinf_rcpp_hello() {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    rcpp_result_gen = Rcpp::wrap(rcpp_hello());
    return rcpp_result_gen;
END_RCPP
}
// single_read_sampling_from_allele_depths
List single_read_sampling_from_allele_depths(CharacterVector file, CharacterVector sample_names, double freq_thresh);
RcppExport SEXP _ecaRbioinf_single_read_sampling_from_allele_depths(SEXP fileSEXP, SEXP sample_namesSEXP, SEXP freq_threshSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< CharacterVector >::type file(fileSEXP);
    Rcpp::traits::input_parameter< CharacterVector >::type sample_names(sample_namesSEXP);
    Rcpp::traits::input_parameter< double >::type freq_thresh(freq_threshSEXP);
    rcpp_result_gen = Rcpp::wrap(single_read_sampling_from_allele_depths(file, sample_names, freq_thresh));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_ecaRbioinf_rcpp_hello", (DL_FUNC) &_ecaRbioinf_rcpp_hello, 0},
    {"_ecaRbioinf_single_read_sampling_from_allele_depths", (DL_FUNC) &_ecaRbioinf_single_read_sampling_from_allele_depths, 3},
    {NULL, NULL, 0}
};

RcppExport void R_init_ecaRbioinf(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
